version: '3.8'
services:
  tomcat-dev:
    image: tomcat:9.0.35-jdk11-openjdk-slim
    volumes: 
      - "./web/static:/usr/local/tomcat/webapps/ROOT"
      - "./build/libs/sample-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/sample.war"
    ports: 
      - "8888:8080"
    restart: always